version: '3.3'

services:
  app:
    tty: true
    image: 'node:18'
    volumes:
      - ./:/app
    command: sh -c "npm install && npm run dev -- --host"
    working_dir: /app
    ports:
      - '5173:5173'
    networks:
      - svelte
networks:
  svelte:
    driver: bridge
